nginx:
    build: .
    dockerfile: Dockerfile.nginx
    links:
        - app
    ports:
        - "88:88"
app:
    build: .
    dockerfile: Dockerfile.node
    links:
        - mongo
    ports:
        - "8080:8080"
mongo:
    build: .
    dockerfile: Dockerfile.mongo
    ports:
        - "27017:27017"